# Installing nginx on all nodes with ansible automation
# Written on YAML
# Ansible Playbook 2.9.27 | Python 2.7.5

---
- name: nginx Installation On Client Machine
  hosts: client-machines
  become: true
  vars:
    ansible_become_pass: 
  tasks:
   - name: install nginx
     package: pkg=nginx state=present

     notify:
      - start nginx

  handlers:
   - name: start nginx
     service: name=nginx state=started
...

